const mongoose=require('mongoose');
const SubSection = require('./SubSection');

const Course=new mongoose.Schema({
  courseName:{
    type:String,
    trim:true,
  },
  courseDescription:{
    type:String,
  },
  instructor:{
    type:mongoose.Schema.Types.ObjectId,
    required:true,
    ref:"User",
  },
  WhatYouWillLearn:{
    type:String,
  },
  courseContent:[{
    type:mongoose.Schema.Types.ObjectId,
    ref:"Section",
  }],
  ratingAndReviews:[{
    type:mongoose.Schema.Types.ObjectId,
    ref:"RatingAndReview",
  }],
  price:{
    type:String,
  },
  thumbnail:{
    type:String,
  },
  tag:{
    type:[String],
    required:true,
  },
  category:{
      type:mongoose.Schema.Types.ObjectId,
      ref:"Category",
  },
  studentsEnrolled:[{
    type:mongoose.Schema.Types.ObjectId,
    ref:"User",
  }],
  instruction:{
    type:[String],
  },
  status:{
    type:String,
    enum:["Draft","Published"],
    default:"Draft",
  },
});
module.exports=mongoose.model("Course",Course);
